In [ ]:
import pandas as pd
import numpy as np

In [3]:
import seaborn as sns

In [8]:
df = pd.read_csv("appendix1.csv")

In [9]:
df

,Species,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,OIL SARDINE,265667.0,244992.0,337390.0,155450.0,145083.0,83048.0,87195.0,251257.0,245420.0,241273.0
1,RIBBON FISHES,177259.0,217100.0,239355.0,193822.0,218736.0,143711.0,141299.0,226554.0,269616.0,229359.0
2,LESSER SARDINES,NaN,NaN,NaN,NaN,170298.0,215676.0,225529.0,169404.0,136878.0,170228.0
3,THREADFIN BREAMS,162764.0,170349.0,157773.0,183518.0,153066.0,122835.0,145446.0,198733.0,207232.0,150969.0
4,OTHER CARANGIDS,77707.0,83602.0,120019.0,126755.0,130439.0,121290.0,160561.0,141149.0,109518.0,112207.0
5,CROAKERS,155383.0,157793.0,150241.0,135451.0,135750.0,117698.0,101287.0,90045.0,103560.0,110142.0
6,OTHER PERCHES,95199.0,171061.0,197258.0,108913.0,95718.0,74474.0,88962.0,132414.0,104176.0,99349.0
7,BOMBAYDUCK,110417.0,144951.0,145115.0,112705.0,117213.0,79178.0,68721.0,55342.0,72806.0,94814.0
8,SCADS,112131.0,105057.0,108010.0,130284.0,73816.0,85792.0,214444.0,163375.0,123758.0,81612.0
9,OTHER CLUPEIDS,63644.0,58579.0,67607.0,52784.0,80603.0,65295.0,57377.0,58341.0,65531.0,80844.0
10,STOLEPHORUS,63382.0,61571.0,64859.0,72792.0,105915.0,59488.0,58501.0,88565.0,67464.0,66944.0
11,CATFISHES,83354.0,80559.0,88177.0,54168.0,65007.0,57635.0,56015.0,62873.0,62354.0,66869.0
12,LIZARD FISHES,77838.0,94817.0,57803.0,69936.0,91144.0,73019.0,81982.0,76377.0,61555.0,62665.0
13,SILVERBELLIES,97663.0,92764.0,89901.0,78261.0,100613.0,60284.0,64922.0,59189.0,44202.0,52465.0
14,ROCK CODS,43146.0,42781.0,53924.0,51433.0,26508.0,33730.0,49714.0,49010.0,69099.0,51865.0

In [16]:
df_num = [col for col in df if pd.api.types.is_numeric_dtype(df[col])]
df_num_only = df[df_num]
df_num_only

,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,265667.0,244992.0,337390.0,155450.0,145083.0,83048.0,87195.0,251257.0,245420.0,241273.0
1,177259.0,217100.0,239355.0,193822.0,218736.0,143711.0,141299.0,226554.0,269616.0,229359.0
2,NaN,NaN,NaN,NaN,170298.0,215676.0,225529.0,169404.0,136878.0,170228.0
3,162764.0,170349.0,157773.0,183518.0,153066.0,122835.0,145446.0,198733.0,207232.0,150969.0
4,77707.0,83602.0,120019.0,126755.0,130439.0,121290.0,160561.0,141149.0,109518.0,112207.0
5,155383.0,157793.0,150241.0,135451.0,135750.0,117698.0,101287.0,90045.0,103560.0,110142.0
6,95199.0,171061.0,197258.0,108913.0,95718.0,74474.0,88962.0,132414.0,104176.0,99349.0
7,110417.0,144951.0,145115.0,112705.0,117213.0,79178.0,68721.0,55342.0,72806.0,94814.0
8,112131.0,105057.0,108010.0,130284.0,73816.0,85792.0,214444.0,163375.0,123758.0,81612.0
9,63644.0,58579.0,67607.0,52784.0,80603.0,65295.0,57377.0,58341.0,65531.0,80844.0
10,63382.0,61571.0,64859.0,72792.0,105915.0,59488.0,58501.0,88565.0,67464.0,66944.0
11,83354.0,80559.0,88177.0,54168.0,65007.0,57635.0,56015.0,62873.0,62354.0,66869.0
12,77838.0,94817.0,57803.0,69936.0,91144.0,73019.0,81982.0,76377.0,61555.0,62665.0
13,97663.0,92764.0,89901.0,78261.0,100613.0,60284.0,64922.0,59189.0,44202.0,52465.0
14,43146.0,42781.0,53924.0,51433.0,26508.0,33730.0,49714.0,49010.0,69099.0,51865.0

In [18]:
df_num_only.to_numpy()

array([[265667., 244992., 337390., 155450., 145083.,  83048.,  87195.,
        251257., 245420., 241273.],
       [177259., 217100., 239355., 193822., 218736., 143711., 141299.,
        226554., 269616., 229359.],
       [    nan,     nan,     nan,     nan, 170298., 215676., 225529.,
        169404., 136878., 170228.],
       [162764., 170349., 157773., 183518., 153066., 122835., 145446.,
        198733., 207232., 150969.],
       [ 77707.,  83602., 120019., 126755., 130439., 121290., 160561.,
        141149., 109518., 112207.],
       [155383., 157793., 150241., 135451., 135750., 117698., 101287.,
         90045., 103560., 110142.],
       [ 95199., 171061., 197258., 108913.,  95718.,  74474.,  88962.,
        132414., 104176.,  99349.],
       [110417., 144951., 145115., 112705., 117213.,  79178.,  68721.,
         55342.,  72806.,  94814.],
       [112131., 105057., 108010., 130284.,  73816.,  85792., 214444.,
        163375., 123758.,  81612.],
       [ 63644.,  58579.,  67607.,  52784.,  80603.,  65295.,  57377.,
         58341.,  65531.,  80844.],
       [ 63382.,  61571.,  64859.,  72792., 105915.,  59488.,  58501.,
         88565.,  67464.,  66944.],
       [ 83354.,  80559.,  88177.,  54168.,  65007.,  57635.,  56015.,
         62873.,  62354.,  66869.],
       [ 77838.,  94817.,  57803.,  69936.,  91144.,  73019.,  81982.,
         76377.,  61555.,  62665.],
       [ 97663.,  92764.,  89901.,  78261., 100613.,  60284.,  64922.,
         59189.,  44202.,  52465.],
       [ 43146.,  42781.,  53924.,  51433.,  26508.,  33730.,  49714.,
         49010.,  69099.,  51865.]])